import { ReactNode } from 'react';
import { Inter } from 'next/font/google';
import { Header, Footer, Banner } from '@app/components';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Banner />
        <Header />
        <main>
          <article>
            {children}
          </article>
        </main>
        <Footer />
      </body>
    </html>
  );
}
